urls.py
from django.conf.urls.defaults import *
from settings import MEDIA_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth.views import login, logout
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'django.views.generic.simple.redirect_to', {'url': '/manager/'}),
    (r'^manager/', include('app.urls')),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
    (r'^admin/(.*)', admin.site.root),
    (r'^accounts/login/$', login),
    (r'^accounts/logout/$', logout),
)

app/forms.py
from django import forms
from models import Item, ItemType, CD, DVD, Performer, PerformerType, Person, Group, Role
from widgets import CalendarWidget

class ItemForm(forms.ModelForm):
    release_date = forms.DateField(widget=CalendarWidget, required=False)
    tags = forms.CharField(required=False)

    def get_form(cls, itemtype):
	if itemtype is None:
	    formType = ItemForm
	elif itemtype.name == 'CD':
	    formType = CDForm
	elif itemtype.name == 'DVD':
	    formType = DVDForm
	else:
	    formType = ItemForm

	return formType

    get_form = classmethod(get_form)

    class Meta:
	model = Item

class CDForm(ItemForm):
    class Meta:
	model = CD

class DVDForm(ItemForm):
    description = forms.CharField(widget=forms.Textarea, required=False)
    class Meta:
	model = DVD

class PerformerForm(forms.ModelForm):
    def get_form(cls, performertype):
	if performertype is None:
	    formType = PerformerForm
	elif performertype.name == 'Person':
	    formType = PersonForm
	elif performertype.name == 'Group':
	    formType = GroupForm
	else:
	    formType = PerformerForm

	return formType


    get_form = classmethod(get_form)

    class Meta:
	model = Performer

class PersonForm(PerformerForm):
    class Meta:
	model = Person

class GroupForm(PerformerForm):
    class Meta:
	model = Group

class RoleForm(forms.ModelForm):
    item = forms.ModelChoiceField(queryset=Item.objects.all().order_by('name'))
    performer = forms.ModelChoiceField(queryset=Performer.objects.all().order_by('name'))
    class Meta:
	model = Role

class SearchForm(forms.Form):
    name = forms.CharField(required=False)
    type = forms.ModelChoiceField(ItemType.objects, required=False)

class ImportForm(forms.Form):
    file = forms.FileField()

templates/app/all_actions.html
{% load i18n %}
<ul>
    <li id='item_add'><a href='{% url app.views.item_add %}'>{% trans 'Add Item' %}</a></li>
    <li id='performer_add'><a href='{% url app.views.performer_add %}'>{% trans 'Add Performer' %}</a></li>
    <li id='search'><a href='{% url app.views.items_search %}'>{% trans 'Search' %}</a></li>
    <li id='import'><a href='{% url app.views.items_import %}'>{% trans 'Import' %}</a></li>
</ul>

templates/app/all_categories.html
<ul>
    <li><a href='{% url app.views.all_categories %}'>All</a></li>
    {% for category in all_categories %}
    <li id='{{ category }}'><a href='{{category.get_absolute_url}}'>{{ category }}</a></li>
    {% endfor %}
</ul>

templates/app/item_cover.html
<a href='{{ coverurl }}'>
<img src='{{ coverurl }}' width='100'/>
</a>

templates/app/item_form.html
{% extends "base.html" %}
{% load app_extras %}

{% block title %}Collection Manager{% endblock %}

{% block head %}

    {{ form.media }}
    <script>
	$(function() {
	    $("#id_tags").autocomplete('{% url app.views.lookup_tags %}', {
		width: 150,
		max: 10,
		highlight: false,
		multiple: true,
		multipleSeparator: " ",
		scroll: true,
		scrollHeight: 300,
		matchContains: true,
		autoFill: true,
		extraParams: {val: function() {
			return document.getElementById('id_tags').value;
		    }
		},
	    });
	});
    </script>

{% endblock %}

{% block content %}

{% if item %}
<h1>{{ item.name }}</h1>
<form enctype="multipart/form-data" action='' method='post'>
    <input type='hidden' name='type' value='{{item.type.pk}}' />
    {% get_cover item %}
{% else %}
<h1>Add new item</h1>
<form enctype="multipart/form-data" action='' method='post'>
{% endif %}

    {% for field in form %}
	<p>
	    {{ field.errors }}
	    {{ field.label_tag }}: {{ field }}
	</p>
    {% endfor %}
    {% if item %}
    <p><label>Roles</label>{% get_item_roles item %}</p>
    {% endif %}

    <input type='submit' value='Save' />
</form>

{% endblock %}

templates/app/item_roles.html
<ul class='roles'>
    {% for role in roles %}
    <li>
    <a href='{{role.get_absolute_url}}'>{{role.get_short_description}}</a>
    <a href='{% url app.views.role_edit role.pk %}'><img src='/media/img/edit.png' /></a>
    <a href='{% url app.views.role_delete role.pk %}'><img src='/media/img/delete.png' /></a>
    </li>
    {% endfor %}
    <a class='add_role' href='{% url app.views.role_item_add item.pk %}'><img src='/media/img/add.png' /><i>add</i></a>
</ul>

templates/app/items_import.html
{% extends "base.html" %}
{% load app_extras %}

{% block title %}Collection Manager{% endblock %}

{% block head %} {{ form.media }} {% endblock %}

{% block content %}

<h1>Import file</h1>
<form enctype="multipart/form-data" action='' method='post'>
    {% for field in form %}
	<p>
	    {{ field.errors }}
	    {{ field.label_tag }}: {{ field }}
	</p>
    {% endfor %}
    <p>
	<input type='submit' value='Save' />
    </p>
</form>

{% endblock %}

templates/app/items_search.html
{% extends "base.html" %}
{% load app_extras %}

{% block title %}Collection Manager{% endblock %}

{% block head %} {{ form.media }} {% endblock %}

{% block content %}

<h1>Search items</h1>
<form action='' method='post'>
    {{ form.as_p }}
    <input type='submit' value='Search' />
</form>
<br />
<hr />
<br />
{% if items_list %}
{% ifnotequal items_list|length 0 %}
<div class='pagination'>
</div>
<div class='items'>
<table>
    {% for item in items_list %}
    <tr class='{% cycle 'odd' 'even' %}'>
	<td class='item_cover'>{% get_cover item %}</td>
	<td><a href='{{ item.get_absolute_url }}'>{{ item }}</a></td>
	<td class='item_type'><a href='{{ item.type.get_absolute_url }}'>{{ item.type }}</a></td>
	<td class='item_tools'><a href='{% url app.views.item_edit item.pk %}'><img src='/media/img/edit.png' /></a>&nbsp;&nbsp;<a href='{% url app.views.item_delete item.pk %}'><img src='/media/img/delete.png' /></a></td>
    </tr>
    {% endfor %}
</table>
</div>
{% else %}
    No results
{% endifnotequal %}
{% else %}
    No results
{% endif %}

{% endblock %}

templates/app/performer_delete.html
{% extends "base.html" %}

{% block title %}Collection Manager{% endblock %}

{% block content %}

<h1>Delete</h1>

Confirm deletion of "{{ performer }}" ?
<a href='{% url app.views.performer_delete_force performer.pk %}'>Y</a> / <a href='{{ performer.get_absolute_url }}'>N</a>

{% endblock %}

templates/app/performer_roles.html
<ul class='roles'>
    {% for role in roles %}
    <li>
    <a href='{{role.get_absolute_url}}'>{{role.type}}</a> of <a href='{{role.item.get_absolute_url}}'>{{role.item}}</a>
    <a href='{% url app.views.role_edit role.pk %}'><img src='/media/img/edit.png' /></a>
    <a href='{% url app.views.role_delete role.pk %}'><img src='/media/img/delete.png' /></a>
    </li>
    {% endfor %}
</ul>

templates/app/performer_view.html
{% extends "base.html" %}
{% load app_extras %}

{% block title %}Collection Manager{% endblock %}

{% block content %}

<h1>{{ performer }}</h1>

<div id='picture'>
</div>

<div id='details'>
    <table>
	<tr>
	    <td>Id</td>
	    <td>{{ performer.pk }}</td>
	</tr>

	<tr>
	    <td>Name</td>
	    <td>{{ performer.name }}</td>
	</tr>

	{% if performer.person %}
	<tr>
	    <td>First Name</td>
	    <td>{{ performer.person.first_name}}</td>
	</tr>
	<tr>
	    <td>Last Name</td>
	    <td>{{ performer.person.last_name }}</td>
	</tr>
	{% else %}
	<tr>
	    <td>Members</td>
	    <td>
		<ul>
		{% for member in performer.group.members.all %}
		<li><a href='{{ member.get_absolute_url }}'>{{ member }}</a></li>
		{% endfor %}
		</ul>
	    </td>
	</tr>
	{% endif %}

	<tr>
	    <td>Type</td>
	    <td>{{ performer.type.name }}</td>
	</tr>
	<tr>
	    <td>Roles</td>
	    <td>
		{% get_performer_roles performer %}
	    </td>
	</tr>
    </table>
</div>
<br />
<div id='actions'>
    <a href='{% url app.views.performer_edit performer.pk %}'>Edit</a> - <a href='{% url app.views.performer_delete performer.pk %}'>Delete</a>
</div>

{% endblock %}

templates/app/quicksearch.html
<form action='{% url app.views.items_search %}' method='post'>
    <input type='text' name='name' id='id_name' value='' size='8' />
    <input type='hidden' name='type' id='id_type' value='' />
    <input type='hidden' name='quicksearch' value='quicksearch' />
    <input type='submit' value='Go' />
</form>

templates/app/role_view.html
{% extends "base.html" %}
{% load app_extras %}

{% block title %}Collection Manager{% endblock %}

{% block content %}

<h1>{{ role }}</h1>

<div id='details'>
    <table>
	<tr>
	    <td>Id</td>
	    <td>{{ role.pk }}</td>
	</tr>
	<tr>
	    <td>Item</td>
	    <td><a href='{{role.item.get_absolute_url}}'>{{role.item}}</a></td>
	</tr>
	<tr>
	    <td>Performer</td>
	    <td><a href='{{role.performer.get_absolute_url}}'>{{ role.performer }}</a></td>
	</tr>
	<tr>
	    <td>Type</td>
	    <td>{{role.type}}</td>
	</tr>
    </table>
</div>
<br />
<div id='actions'>
    <a href='{% url app.views.role_edit role.pk %}'>Edit</a> - <a href='{% url app.views.role_delete role.pk %}'>Delete</a>
</div>

{% endblock %}

templates/app/select_categories.html
<select name='{{name}}'>
    {% for category in all_categories %}
	{% ifequal category.name default.name %}
	    <option value='{{category}}' selected='selected'>{{category}}</option>
	{% else %}
	    <option value='{{category}}'>{{category}}</option>
	{% endifequal %}
    {% endfor %}
</select>

templates/app/tag_cloud.html
{% load tagging_tags %}

{% tag_cloud_for_model app.Item as tag_list with steps=4 %}
{% for tag in tag_list %}
<span class="tag{{ tag.font_size }}"><a href='{% url app.views.tag tag.pk %}' title='{{ tag.count }}'>{{ tag }}</a></span>
{% endfor %}